version: "3.9"

services:
  referral_db:
    container_name: referral_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - referral_db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - referral_system_network

volumes:
  referral_db_volume:
    name: referral_db_volume

networks:
  referral_system_network:
    name: referral_system_network
